#!/bin/bash

module swap intel-fc intel-fc/15.0.3.187
module swap intel-cc intel-cc/15.0.3.187
module swap openmpi openmpi/1.8.8
module load netcdf/4.3.3.1
export WRFIO_NCD_LARGE_FILE_SUPPORT=1

# Un-comment to compile with chemistry
#export WRF_CHEM=1

./configure

# -V: to send over all the environment variables, in particular from the modules loaded
# for the configuration.

qsub -V -N wrf_compile << EOF_compile
#!/bin/bash
#PBS -l walltime=1:00:00
#PBS -l mem=5GB
#PBS -l ncpus=4
#PBS -j oe
#PBS -q express
#PBS -l wd
#PBS -l software=intel-cc/2:intel-fc/2

export J="-j \$PBS_NCPUS"

./compile em_real
EOF_compile

