#!/bin/bash

module load intel-fc/15.0.3.187
module load intel-cc/15.0.3.187
module load openmpi/1.8.8
module load netcdf/4.3.3.1
module load ncl/6.3.0

./configure

# -V: to send over all the environment variables, in particular from the modules loaded
# for the configuration.

qsub -V -N wps_compile << EOF_compile
#!/bin/bash
#PBS -l walltime=1800
#PBS -l mem=600MB
#PBS -l ncpus=1
#PBS -q express
#PBS -l wd
#PBS -j oe
#PBS -l software=intel-cc/2:intel-fc/2

./compile
EOF_compile
